import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = (): JSX.Element => (
  <div>
    <Head>
      <title>My Profile</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>Welcome to My Profile</h1>
    </main>
  </div>
)

export default Home
